name: mw

services:
  searxng:
    image: searxng/searxng:2024.11.8-2fbf15ecc
    restart: unless-stopped
    volumes:
      - ./config/searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - mw-net

  perplexica-backend:
    image: airndlab/perplexica-backend:2024.11.10-13-55
    restart: unless-stopped
    depends_on:
      - searxng
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    ports:
      - 3001:3001
    volumes:
      - ./data/perplexica-backend:/home/perplexica/data
      - ./config/web.config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mw-net

  perplexica-frontend:
    image: airndlab/perplexica-frontend:2024.11.12-06-31
    restart: unless-stopped
    depends_on:
      - perplexica-backend
    environment:
      - NEXT_PUBLIC_API_URL=http://158.160.68.33:3001/api
      - NEXT_PUBLIC_WS_URL=ws://158.160.68.33:3001
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    ports:
      - 80:3000
    networks:
      - mw-net

  metabase:
    image: metabase/metabase:v0.50.29
    restart: unless-stopped
    ports:
      - 3003:3000
    volumes:
      - ./data:/data
    environment:
      - MB_DB_FILE=/data/metabase.db
      - MB_DB_TYPE=h2

  chroma:
    image: chromadb/chroma:0.5.18
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - mw-net

networks:
  mw-net:

volumes:
  chroma-data:
