model: Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4
embedding_model: deepvk/USER-bge-m3
cross_encoder_model: qilowoq/bge-reranker-v2-m3-en-ru

split_function:
  max_chunk_size: 300
  overlap: 0

rag_gen_kwargs:
  max_tokens: 2048
  top_p: 0.8
  temperature: 0.3

json_gen_kwargs:
  max_tokens: 512
  top_p: 0.9
  temperature: 0.3
  frequency_penalty: 1.2

bm25_retriever:
  top_k: 5

embedding_retriever:
  top_k: 5

document_joiner:
  threshold: 0.0
  top_k: 10

cross_encoder:
  top_k: 4
  threshold: 0.1

vlm_model: Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4
colvision_model: vidore/colpali-v1.2

vlm_top_k: 1

document_store:
  reindex: false
  load_path: "main_document_store"
